### ISSUE TITLE
Mug Installer @ develop is broken

### ISSUE THREAD

**Issue by StanHash** [FireEmblemUniverse/VBA-Blitz-Tendency#122]
I know Colorz knows about that but may as well still note it here.

[Mugs/Mug Installer.event](https://github.com/FireEmblemUniverse/VBA-Blitz-Tendency/blob/master/Mugs/Mug%20Installer.event) has residual merge conflict notes thing whatever and all. Also Zane.png does not exist.

#121 fixes this

**Comment by Crazycolorz5** [comment]
Fixed in #121 and #128.
